import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ConfirmSubmit } from '@/components/aeo/ConfirmSubmit'
import { Card } from '@/components/ui/Card'
import { loadRunDetail } from '@/lib/aeo/admin'
import { LEAD_STATUSES } from '@/lib/aeo/lead-filters'
import { verdictOf, type Verdict } from '@/lib/aeo/report'
import { requireSession } from '@/lib/session'
import { deleteLead, rerunSnapshot, updateLeadStatus } from '../actions'

export const dynamic = 'force-dynamic'
export const metadata = { title: 'Run | BusinessPulse' }

type Props = { params: Promise<{ runId: string }> }

const VERDICTS: Record<Verdict, { label: string; className: string }> = {
  cited: { label: 'Cited', className: 'bg-success/10 text-success' },
  directory: { label: 'Directory only', className: 'bg-amber-100 text-amber-800' },
  named: { label: 'Named', className: 'bg-amber-100 text-amber-800' },
  absent: { label: 'Absent', className: 'bg-danger/10 text-danger' },
  no_search: { label: 'No search', className: 'bg-gray-100 text-text-secondary' },
  error: { label: 'Error', className: 'bg-gray-100 text-text-secondary' },
}

function formatDateTime(date: Date | null): string {
  if (!date) return '-'
  return new Intl.DateTimeFormat('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'America/New_York',
  }).format(date)
}

function usd(value: string | number | null): string {
  return `$${Number(value ?? 0).toFixed(4)}`
}

/** Links come from third-party API responses: only plain web URLs become clickable. */
function safeHref(url: string): string | null {
  try {
    const parsed = new URL(url)
    return parsed.protocol === 'https:' || parsed.protocol === 'http:' ? parsed.toString() : null
  } catch {
    return null
  }
}

function Fact({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <dt className="text-xs text-text-secondary">{label}</dt>
      <dd className="mt-0.5 text-sm text-dark">{children}</dd>
    </div>
  )
}

export default async function RunDetailPage({ params }: Props) {
  // Layouts and pages render in parallel, so the layout's session check alone
  // wouldn't stop this page from loading and streaming the run's data.
  await requireSession()
  const { runId } = await params
  const detail = await loadRunDetail(runId)
  if (!detail) notFound()

  const { run, requests, results, panelName } = detail
  const title = requests[0]?.businessName ?? run.domain
  const generated = run.generatedPanel
  const answered = results.filter((r) => !r.error).length

  return (
    <div className="space-y-6">
      <div>
        <Link href="/dashboard/aeo" className="text-sm text-primary hover:underline">
          Leads
        </Link>
        <div className="mt-2 flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-dark">{title}</h1>
            <p className="mt-1 text-text-secondary">{run.domain}</p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <a
              href={`/report/${run.publicId}`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-md border border-border bg-white px-3 py-1.5 text-sm font-medium text-dark hover:bg-gray-50"
            >
              Public report
            </a>
            <form action={rerunSnapshot}>
              <input type="hidden" name="runId" value={run.id} />
              <ConfirmSubmit
                message="Start a fresh run for this business? It spends API money, skips the 30-day reuse and the daily cap, and moves these requests to the new run. The customer isn't emailed again."
                className="bg-primary text-white hover:bg-primary/90"
              >
                Re-run
              </ConfirmSubmit>
            </form>
          </div>
        </div>
      </div>

      <Card>
        <dl className="grid gap-4 sm:grid-cols-3 lg:grid-cols-4">
          <Fact label="Status">
            <span className={run.status === 'failed' ? 'text-danger' : undefined}>{run.status}</span>
            {run.bypassSpendCap && <span className="ml-2 text-xs text-text-secondary">(admin re-run)</span>}
          </Fact>
          <Fact label="Cited">
            {run.status === 'done' ? `${run.citedCount} of ${run.questionCount} answered` : '-'}
          </Fact>
          <Fact label="Answers stored">
            {answered} of {results.length}
          </Fact>
          <Fact label="Cost">{usd(run.costUsd)}</Fact>
          <Fact label="Panel">
            {run.panelSource === 'canned'
              ? `${panelName ?? run.panelSlug} (v${run.panelVersion ?? '?'})`
              : generated
                ? `Generated by ${generated.model}${generated.siteRead ? '' : ', site not read'}`
                : 'Generated (not yet)'}
          </Fact>
          <Fact label="Attempts">{run.attempts}</Fact>
          <Fact label="Created">{formatDateTime(run.createdAt)}</Fact>
          <Fact label="Finished">{formatDateTime(run.finishedAt)}</Fact>
        </dl>
        {run.error && (
          <p className="mt-4 whitespace-pre-wrap break-words rounded-md bg-danger/5 p-3 text-sm text-danger">{run.error}</p>
        )}
      </Card>

      <section>
        <h2 className="text-lg font-semibold text-dark">Requests</h2>
        {requests.length === 0 ? (
          <p className="mt-2 text-sm text-text-secondary">No requests use this run (it was re-run or its requests were deleted).</p>
        ) : (
          <div className="mt-3 space-y-3">
            {requests.map((request) => (
              <Card key={request.id} className="p-4">
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <dl className="grid flex-1 gap-3 sm:grid-cols-3">
                    <Fact label="Business">{request.businessName}</Fact>
                    <Fact label="Email">
                      {request.email}
                      {request.contactConsent && <span className="ml-2 text-xs text-success">OK to contact</span>}
                    </Fact>
                    <Fact label="Service">
                      {request.service}, {request.city}, {request.state}
                    </Fact>
                    <Fact label="Submitted">{formatDateTime(request.createdAt)}</Fact>
                    <Fact label="Verified">{formatDateTime(request.verifiedAt)}</Fact>
                    <Fact label="Report emailed">{formatDateTime(request.reportEmailedAt)}</Fact>
                    <Fact label="IP address">{request.ipAddress ?? '-'}</Fact>
                  </dl>
                  <div className="flex flex-col items-end gap-2">
                    <form action={updateLeadStatus} className="flex items-center gap-2">
                      <input type="hidden" name="requestId" value={request.id} />
                      <input type="hidden" name="runId" value={run.id} />
                      <select
                        name="status"
                        defaultValue={request.leadStatus}
                        aria-label="Lead status"
                        className="rounded-md border border-border bg-white px-2 py-1.5 text-sm text-dark"
                      >
                        {LEAD_STATUSES.map((s) => (
                          <option key={s} value={s}>
                            {s}
                          </option>
                        ))}
                      </select>
                      <button
                        type="submit"
                        className="rounded-md border border-border bg-white px-3 py-1.5 text-sm font-medium text-dark hover:bg-gray-50"
                      >
                        Save
                      </button>
                    </form>
                    <form action={deleteLead}>
                      <input type="hidden" name="requestId" value={request.id} />
                      <ConfirmSubmit
                        message={`Permanently delete ${request.email}'s request${requests.length === 1 ? ' and this run with all its results' : ''}? This can't be undone.`}
                        className="text-danger hover:bg-danger/5"
                      >
                        Delete
                      </ConfirmSubmit>
                    </form>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </section>

      <section>
        <h2 className="text-lg font-semibold text-dark">Questions and answers</h2>
        {results.length === 0 ? (
          <p className="mt-2 text-sm text-text-secondary">No results yet.</p>
        ) : (
          <div className="mt-3 divide-y divide-border rounded-lg border border-border bg-white">
            {results.map((result) => {
              const verdict = VERDICTS[verdictOf(result)]
              const citedRivals = result.rivals.filter((r) => r.cited)
              return (
                <details key={result.id} className="group px-4 py-3">
                  <summary className="flex cursor-pointer list-none flex-wrap items-center gap-2 text-sm">
                    <span className={`rounded px-2 py-0.5 text-xs font-medium ${verdict.className}`}>{verdict.label}</span>
                    <span className="text-xs text-text-secondary">{result.category}</span>
                    <span className="text-dark">{result.query}</span>
                  </summary>
                  <div className="mt-3 space-y-3 text-sm">
                    {result.error && <p className="text-danger">{result.error}</p>}
                    {result.answer && (
                      <p className="whitespace-pre-wrap break-words text-text-secondary">{result.answer}</p>
                    )}
                    {citedRivals.length > 0 && (
                      <p className="text-xs text-text-secondary">
                        Rivals cited: <span className="text-dark">{citedRivals.map((r) => r.host).join(', ')}</span>
                      </p>
                    )}
                    {result.sources.length > 0 && (
                      <ol className="list-decimal space-y-1 pl-5 text-xs">
                        {result.sources.map((source, index) => {
                          const href = safeHref(source.url)
                          return (
                            <li key={`${source.url}-${index}`} className="break-all text-text-secondary">
                              {href ? (
                                <a href={href} target="_blank" rel="noopener noreferrer nofollow" className="text-primary hover:underline">
                                  {source.title || source.url}
                                </a>
                              ) : (
                                source.title || source.url
                              )}
                              {source.cited && <span className="ml-1 text-success">cited</span>}
                            </li>
                          )
                        })}
                      </ol>
                    )}
                    <p className="text-xs text-text-secondary">
                      {result.engine} {result.model} · {result.searches} searches · {result.inputTokens} in / {result.outputTokens} out · {usd(result.costUsd)}
                    </p>
                  </div>
                </details>
              )
            })}
          </div>
        )}
      </section>
    </div>
  )
}
